# STAGE 1: Build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /app
COPY *.csproj ./
RUN dotnet restore
COPY . ./
RUN dotnet publish -c Release -o /app/publish

# STAGE 2: Runtime  ? MUST be 8.0
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime

WORKDIR /app
COPY --from=build /app/publish .
EXPOSE 5284
ENTRYPOINT ["dotnet", "TodoApi.dll"]